### ISSUE TITLE
Crash when armor value is very high

### ISSUE THREAD

**Issue by kjmaster1** [LocusWay/OverpoweredArmorBar#12] opened 2018-09-12 14:03 UTC
While playing ATM 3 Remix I used Construct's armory and Career Bees to achieve a very high armor value and it caused this crash:
https://paste.dimdev.org/hicanorohu.sql

**Comment by LocusWay** [comment] 2018-09-12 23:15
Thanks for including the crash dump.

It looks like you are running v0.2.1, there is a known crash issue with impressively large amounts of armor (or when you remove too many of the colors from the settings).
That issue should be fixed on v0.3.2.

That gives you two fixes and a workaround
1) Manually update to v0.3.2 and check if the issue is resolved
2) Ask the mod pack author to update the pack. I would recommend testing the new version first to ensure the updated pack would solve your issue.

Workaround: Edit your config file (or use the in game UI) to include some additional colors for your vast amounts of armor to work around the issue until the pack is updated.

**Closed** 2018-09-22 02:46 UTC
